nome = input('Olá, qual é o seu nome? ')
print('Muito prazer {}!'.format(nome))
print('Muito prazer {:20}!'.format(nome))
print('Muito prazer {:>20}!'.format(nome))
print('Muito prazer {:<20}!'.format(nome))
print('Muito prazer {:^20}!'.format(nome))
print('Muito prazer {:@^20}!'.format(nome))
